name: Déploiement

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build le site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Téléverser l'artéfact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
  deploy:
    name: Déployer le site
    needs: build

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4